grpc:
    host: "127.0.0.1"
    port: 9888
    enable: true

ftp:
    addr:
        host: "192.168.0.105"
        port: 22
        enable: true
    user: "-----------"
    pass: "------------"
    remotedirectory: "------------"

pathtodb: "---------------"
namedb: "links.db"

source:
    workPath: "---------------------"

cache:
    host: "127.0.0.1"
    port: 8123
    enable: true
