// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: docs/proto/v1/sender.proto

// Имя пакета

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SenderHealtheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SenderHealtheckResponse) Reset() {
	*x = SenderHealtheckResponse{}
	mi := &file_docs_proto_v1_sender_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderHealtheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderHealtheckResponse) ProtoMessage() {}

func (x *SenderHealtheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_sender_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderHealtheckResponse.ProtoReflect.Descriptor instead.
func (*SenderHealtheckResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_sender_proto_rawDescGZIP(), []int{0}
}

func (x *SenderHealtheckResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type LoadHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         []*FileInfo            `protobuf:"bytes,1,rep,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadHistoryResponse) Reset() {
	*x = LoadHistoryResponse{}
	mi := &file_docs_proto_v1_sender_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadHistoryResponse) ProtoMessage() {}

func (x *LoadHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_sender_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadHistoryResponse.ProtoReflect.Descriptor instead.
func (*LoadHistoryResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_sender_proto_rawDescGZIP(), []int{1}
}

func (x *LoadHistoryResponse) GetQueue() []*FileInfo {
	if x != nil {
		return x.Queue
	}
	return nil
}

type FileOnWork struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Link           string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Filename       string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MoveTo         string                 `protobuf:"bytes,3,opt,name=moveTo,proto3" json:"moveTo,omitempty"`
	TargetQuantity int64                  `protobuf:"varint,4,opt,name=targetQuantity,proto3" json:"targetQuantity,omitempty"`
	Procentage     float64                `protobuf:"fixed64,5,opt,name=procentage,proto3" json:"procentage,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CurrentSize    float64                `protobuf:"fixed64,7,opt,name=currentSize,proto3" json:"currentSize,omitempty"`
	TotalSize      float64                `protobuf:"fixed64,8,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
	Message        string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileOnWork) Reset() {
	*x = FileOnWork{}
	mi := &file_docs_proto_v1_sender_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOnWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOnWork) ProtoMessage() {}

func (x *FileOnWork) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_sender_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOnWork.ProtoReflect.Descriptor instead.
func (*FileOnWork) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_sender_proto_rawDescGZIP(), []int{2}
}

func (x *FileOnWork) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *FileOnWork) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileOnWork) GetMoveTo() string {
	if x != nil {
		return x.MoveTo
	}
	return ""
}

func (x *FileOnWork) GetTargetQuantity() int64 {
	if x != nil {
		return x.TargetQuantity
	}
	return 0
}

func (x *FileOnWork) GetProcentage() float64 {
	if x != nil {
		return x.Procentage
	}
	return 0
}

func (x *FileOnWork) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileOnWork) GetCurrentSize() float64 {
	if x != nil {
		return x.CurrentSize
	}
	return 0
}

func (x *FileOnWork) GetTotalSize() float64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FileOnWork) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoadStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinksInWork   []*FileOnWork          `protobuf:"bytes,1,rep,name=linksInWork,proto3" json:"linksInWork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadStatusResponse) Reset() {
	*x = LoadStatusResponse{}
	mi := &file_docs_proto_v1_sender_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadStatusResponse) ProtoMessage() {}

func (x *LoadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_sender_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadStatusResponse.ProtoReflect.Descriptor instead.
func (*LoadStatusResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_sender_proto_rawDescGZIP(), []int{3}
}

func (x *LoadStatusResponse) GetLinksInWork() []*FileOnWork {
	if x != nil {
		return x.LinksInWork
	}
	return nil
}

type ToQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	TargetQuality int32                  `protobuf:"varint,4,opt,name=targetQuality,proto3" json:"targetQuality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToQueueRequest) Reset() {
	*x = ToQueueRequest{}
	mi := &file_docs_proto_v1_sender_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToQueueRequest) ProtoMessage() {}

func (x *ToQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_sender_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToQueueRequest.ProtoReflect.Descriptor instead.
func (*ToQueueRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_sender_proto_rawDescGZIP(), []int{4}
}

func (x *ToQueueRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ToQueueRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ToQueueRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ToQueueRequest) GetTargetQuality() int32 {
	if x != nil {
		return x.TargetQuality
	}
	return 0
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TargetQuality string                 `protobuf:"bytes,3,opt,name=targetQuality,proto3" json:"targetQuality,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Message       *string                `protobuf:"bytes,5,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_docs_proto_v1_sender_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_sender_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_sender_proto_rawDescGZIP(), []int{5}
}

func (x *FileInfo) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *FileInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileInfo) GetTargetQuality() string {
	if x != nil {
		return x.TargetQuality
	}
	return ""
}

func (x *FileInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *FileInfo) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_docs_proto_v1_sender_proto protoreflect.FileDescriptor

const file_docs_proto_v1_sender_proto_rawDesc = "" +
	"\n" +
	"\x1adocs/proto/v1/sender.proto\x12\agrpc.v1\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\x17SenderHealtheckResponse\x12\x1d\n" +
	"\amessage\x18\x01 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\">\n" +
	"\x13LoadHistoryResponse\x12'\n" +
	"\x05queue\x18\x01 \x03(\v2\x11.grpc.v1.FileInfoR\x05queue\"\x8e\x02\n" +
	"\n" +
	"FileOnWork\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x16\n" +
	"\x06moveTo\x18\x03 \x01(\tR\x06moveTo\x12&\n" +
	"\x0etargetQuantity\x18\x04 \x01(\x03R\x0etargetQuantity\x12\x1e\n" +
	"\n" +
	"procentage\x18\x05 \x01(\x01R\n" +
	"procentage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12 \n" +
	"\vcurrentSize\x18\a \x01(\x01R\vcurrentSize\x12\x1c\n" +
	"\ttotalSize\x18\b \x01(\x01R\ttotalSize\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\"K\n" +
	"\x12LoadStatusResponse\x125\n" +
	"\vlinksInWork\x18\x01 \x03(\v2\x13.grpc.v1.FileOnWorkR\vlinksInWork\"\x82\x01\n" +
	"\x0eToQueueRequest\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1a\n" +
	"\buserName\x18\x03 \x01(\tR\buserName\x12$\n" +
	"\rtargetQuality\x18\x04 \x01(\x05R\rtargetQuality\"\xa9\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12$\n" +
	"\rtargetQuality\x18\x03 \x01(\tR\rtargetQuality\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x05 \x01(\tH\x01R\amessage\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_message2\xde\x02\n" +
	"\x06Sender\x12<\n" +
	"\aToQueue\x12\x17.grpc.v1.ToQueueRequest\x1a\x16.google.protobuf.Empty\"\x00\x12=\n" +
	"\tCleanDone\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12C\n" +
	"\n" +
	"LoadStatus\x12\x16.google.protobuf.Empty\x1a\x1b.grpc.v1.LoadStatusResponse\"\x00\x12C\n" +
	"\tLoadQueue\x12\x16.google.protobuf.Empty\x1a\x1c.grpc.v1.LoadHistoryResponse\"\x00\x12M\n" +
	"\x0fSenderHealtheck\x12\x16.google.protobuf.Empty\x1a .grpc.v1.SenderHealtheckResponse\"\x00B\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_docs_proto_v1_sender_proto_rawDescOnce sync.Once
	file_docs_proto_v1_sender_proto_rawDescData []byte
)

func file_docs_proto_v1_sender_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_sender_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_sender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_sender_proto_rawDesc), len(file_docs_proto_v1_sender_proto_rawDesc)))
	})
	return file_docs_proto_v1_sender_proto_rawDescData
}

var file_docs_proto_v1_sender_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_docs_proto_v1_sender_proto_goTypes = []any{
	(*SenderHealtheckResponse)(nil), // 0: grpc.v1.SenderHealtheckResponse
	(*LoadHistoryResponse)(nil),     // 1: grpc.v1.LoadHistoryResponse
	(*FileOnWork)(nil),              // 2: grpc.v1.FileOnWork
	(*LoadStatusResponse)(nil),      // 3: grpc.v1.LoadStatusResponse
	(*ToQueueRequest)(nil),          // 4: grpc.v1.ToQueueRequest
	(*FileInfo)(nil),                // 5: grpc.v1.FileInfo
	(*emptypb.Empty)(nil),           // 6: google.protobuf.Empty
}
var file_docs_proto_v1_sender_proto_depIdxs = []int32{
	5, // 0: grpc.v1.LoadHistoryResponse.queue:type_name -> grpc.v1.FileInfo
	2, // 1: grpc.v1.LoadStatusResponse.linksInWork:type_name -> grpc.v1.FileOnWork
	4, // 2: grpc.v1.Sender.ToQueue:input_type -> grpc.v1.ToQueueRequest
	6, // 3: grpc.v1.Sender.CleanDone:input_type -> google.protobuf.Empty
	6, // 4: grpc.v1.Sender.LoadStatus:input_type -> google.protobuf.Empty
	6, // 5: grpc.v1.Sender.LoadQueue:input_type -> google.protobuf.Empty
	6, // 6: grpc.v1.Sender.SenderHealtheck:input_type -> google.protobuf.Empty
	6, // 7: grpc.v1.Sender.ToQueue:output_type -> google.protobuf.Empty
	6, // 8: grpc.v1.Sender.CleanDone:output_type -> google.protobuf.Empty
	3, // 9: grpc.v1.Sender.LoadStatus:output_type -> grpc.v1.LoadStatusResponse
	1, // 10: grpc.v1.Sender.LoadQueue:output_type -> grpc.v1.LoadHistoryResponse
	0, // 11: grpc.v1.Sender.SenderHealtheck:output_type -> grpc.v1.SenderHealtheckResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_sender_proto_init() }
func file_docs_proto_v1_sender_proto_init() {
	if File_docs_proto_v1_sender_proto != nil {
		return
	}
	file_docs_proto_v1_sender_proto_msgTypes[0].OneofWrappers = []any{}
	file_docs_proto_v1_sender_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_sender_proto_rawDesc), len(file_docs_proto_v1_sender_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_sender_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_sender_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_sender_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_sender_proto = out.File
	file_docs_proto_v1_sender_proto_goTypes = nil
	file_docs_proto_v1_sender_proto_depIdxs = nil
}
