// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: docs/proto/v1/sender.proto

// Имя пакета

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealtheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealtheckResponse) Reset() {
	*x = HealtheckResponse{}
	mi := &file_docs_proto_v1_sender_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealtheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealtheckResponse) ProtoMessage() {}

func (x *HealtheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_sender_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealtheckResponse.ProtoReflect.Descriptor instead.
func (*HealtheckResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_sender_proto_rawDescGZIP(), []int{0}
}

func (x *HealtheckResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         []*FileInfo            `protobuf:"bytes,1,rep,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_docs_proto_v1_sender_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_sender_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_sender_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryResponse) GetQueue() []*FileInfo {
	if x != nil {
		return x.Queue
	}
	return nil
}

type OnWork struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Link           string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Filename       string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MoveTo         string                 `protobuf:"bytes,3,opt,name=moveTo,proto3" json:"moveTo,omitempty"`
	TargetQuantity int64                  `protobuf:"varint,4,opt,name=targetQuantity,proto3" json:"targetQuantity,omitempty"`
	Procentage     float64                `protobuf:"fixed64,5,opt,name=procentage,proto3" json:"procentage,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CurrentSize    float64                `protobuf:"fixed64,7,opt,name=currentSize,proto3" json:"currentSize,omitempty"`
	TotalSize      float64                `protobuf:"fixed64,8,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
	Message        string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OnWork) Reset() {
	*x = OnWork{}
	mi := &file_docs_proto_v1_sender_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnWork) ProtoMessage() {}

func (x *OnWork) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_sender_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnWork.ProtoReflect.Descriptor instead.
func (*OnWork) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_sender_proto_rawDescGZIP(), []int{2}
}

func (x *OnWork) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *OnWork) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *OnWork) GetMoveTo() string {
	if x != nil {
		return x.MoveTo
	}
	return ""
}

func (x *OnWork) GetTargetQuantity() int64 {
	if x != nil {
		return x.TargetQuantity
	}
	return 0
}

func (x *OnWork) GetProcentage() float64 {
	if x != nil {
		return x.Procentage
	}
	return 0
}

func (x *OnWork) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OnWork) GetCurrentSize() float64 {
	if x != nil {
		return x.CurrentSize
	}
	return 0
}

func (x *OnWork) GetTotalSize() float64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *OnWork) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinksInWork   []*OnWork              `protobuf:"bytes,1,rep,name=linksInWork,proto3" json:"linksInWork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_docs_proto_v1_sender_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_sender_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_sender_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetLinksInWork() []*OnWork {
	if x != nil {
		return x.LinksInWork
	}
	return nil
}

type SetToQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	TargetQuality int32                  `protobuf:"varint,3,opt,name=targetQuality,proto3" json:"targetQuality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetToQueueRequest) Reset() {
	*x = SetToQueueRequest{}
	mi := &file_docs_proto_v1_sender_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetToQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetToQueueRequest) ProtoMessage() {}

func (x *SetToQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_sender_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetToQueueRequest.ProtoReflect.Descriptor instead.
func (*SetToQueueRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_sender_proto_rawDescGZIP(), []int{4}
}

func (x *SetToQueueRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *SetToQueueRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SetToQueueRequest) GetTargetQuality() int32 {
	if x != nil {
		return x.TargetQuality
	}
	return 0
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TargetQuality string                 `protobuf:"bytes,3,opt,name=targetQuality,proto3" json:"targetQuality,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Message       *string                `protobuf:"bytes,5,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_docs_proto_v1_sender_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_sender_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_sender_proto_rawDescGZIP(), []int{5}
}

func (x *FileInfo) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *FileInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileInfo) GetTargetQuality() string {
	if x != nil {
		return x.TargetQuality
	}
	return ""
}

func (x *FileInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *FileInfo) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_docs_proto_v1_sender_proto protoreflect.FileDescriptor

const file_docs_proto_v1_sender_proto_rawDesc = "" +
	"\n" +
	"\x1adocs/proto/v1/sender.proto\x12\agrpc.v1\x1a\x1bgoogle/protobuf/empty.proto\">\n" +
	"\x11HealtheckResponse\x12\x1d\n" +
	"\amessage\x18\x01 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\":\n" +
	"\x0fHistoryResponse\x12'\n" +
	"\x05queue\x18\x01 \x03(\v2\x11.grpc.v1.FileInfoR\x05queue\"\x8a\x02\n" +
	"\x06OnWork\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x16\n" +
	"\x06moveTo\x18\x03 \x01(\tR\x06moveTo\x12&\n" +
	"\x0etargetQuantity\x18\x04 \x01(\x03R\x0etargetQuantity\x12\x1e\n" +
	"\n" +
	"procentage\x18\x05 \x01(\x01R\n" +
	"procentage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12 \n" +
	"\vcurrentSize\x18\a \x01(\x01R\vcurrentSize\x12\x1c\n" +
	"\ttotalSize\x18\b \x01(\x01R\ttotalSize\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\"C\n" +
	"\x0eStatusResponse\x121\n" +
	"\vlinksInWork\x18\x01 \x03(\v2\x0f.grpc.v1.OnWorkR\vlinksInWork\"i\n" +
	"\x11SetToQueueRequest\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12$\n" +
	"\rtargetQuality\x18\x03 \x01(\x05R\rtargetQuality\"\xa9\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12$\n" +
	"\rtargetQuality\x18\x03 \x01(\tR\rtargetQuality\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x05 \x01(\tH\x01R\amessage\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_message2\xcb\x02\n" +
	"\x06Sender\x12B\n" +
	"\n" +
	"SetToQueue\x12\x1a.grpc.v1.SetToQueueRequest\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\fCleanHistory\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12;\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a\x17.grpc.v1.StatusResponse\"\x00\x12;\n" +
	"\x05Queue\x12\x16.google.protobuf.Empty\x1a\x18.grpc.v1.HistoryResponse\"\x00\x12A\n" +
	"\tHealtheck\x12\x16.google.protobuf.Empty\x1a\x1a.grpc.v1.HealtheckResponse\"\x00B\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_docs_proto_v1_sender_proto_rawDescOnce sync.Once
	file_docs_proto_v1_sender_proto_rawDescData []byte
)

func file_docs_proto_v1_sender_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_sender_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_sender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_sender_proto_rawDesc), len(file_docs_proto_v1_sender_proto_rawDesc)))
	})
	return file_docs_proto_v1_sender_proto_rawDescData
}

var file_docs_proto_v1_sender_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_docs_proto_v1_sender_proto_goTypes = []any{
	(*HealtheckResponse)(nil), // 0: grpc.v1.HealtheckResponse
	(*HistoryResponse)(nil),   // 1: grpc.v1.HistoryResponse
	(*OnWork)(nil),            // 2: grpc.v1.OnWork
	(*StatusResponse)(nil),    // 3: grpc.v1.StatusResponse
	(*SetToQueueRequest)(nil), // 4: grpc.v1.SetToQueueRequest
	(*FileInfo)(nil),          // 5: grpc.v1.FileInfo
	(*emptypb.Empty)(nil),     // 6: google.protobuf.Empty
}
var file_docs_proto_v1_sender_proto_depIdxs = []int32{
	5, // 0: grpc.v1.HistoryResponse.queue:type_name -> grpc.v1.FileInfo
	2, // 1: grpc.v1.StatusResponse.linksInWork:type_name -> grpc.v1.OnWork
	4, // 2: grpc.v1.Sender.SetToQueue:input_type -> grpc.v1.SetToQueueRequest
	6, // 3: grpc.v1.Sender.CleanHistory:input_type -> google.protobuf.Empty
	6, // 4: grpc.v1.Sender.Status:input_type -> google.protobuf.Empty
	6, // 5: grpc.v1.Sender.Queue:input_type -> google.protobuf.Empty
	6, // 6: grpc.v1.Sender.Healtheck:input_type -> google.protobuf.Empty
	6, // 7: grpc.v1.Sender.SetToQueue:output_type -> google.protobuf.Empty
	6, // 8: grpc.v1.Sender.CleanHistory:output_type -> google.protobuf.Empty
	3, // 9: grpc.v1.Sender.Status:output_type -> grpc.v1.StatusResponse
	1, // 10: grpc.v1.Sender.Queue:output_type -> grpc.v1.HistoryResponse
	0, // 11: grpc.v1.Sender.Healtheck:output_type -> grpc.v1.HealtheckResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_sender_proto_init() }
func file_docs_proto_v1_sender_proto_init() {
	if File_docs_proto_v1_sender_proto != nil {
		return
	}
	file_docs_proto_v1_sender_proto_msgTypes[0].OneofWrappers = []any{}
	file_docs_proto_v1_sender_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_sender_proto_rawDesc), len(file_docs_proto_v1_sender_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_sender_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_sender_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_sender_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_sender_proto = out.File
	file_docs_proto_v1_sender_proto_goTypes = nil
	file_docs_proto_v1_sender_proto_depIdxs = nil
}
